/**
 ******************************************************************************
 * @file      sysmem.c
 * @author    Generated by STM32CubeIDE
 * @brief     STM32CubeIDE System Memory calls file
 *
 *            For more information about which C functions
 *            need which of these lowlevel functions
 *            please consult the newlib libc manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <errno.h>
#include <stdint.h>
#include <cstdlib>
#include <cassert>
#include <cstring>
#include <inttypes.h>

#include "Interfaces/IKernel.hpp"

// The section ".sys_calls" will be at the beginning of the data section which
// will be replaced.
// The value DUMMY_KERNEL_ADDR is a dummy value which will be sanity checked
// before being replaced with actual address on the mcu during app loading
const IKernel *kernel __attribute__((unused, section(".sys_calls"))) = (IKernel*) (DUMMY_KERNEL_ADDR);

extern void (*__preinit_array_start []) (void) __attribute__((weak));
extern void (*__preinit_array_end [])   (void) __attribute__((weak));
extern void (*__init_array_start [])    (void) __attribute__((weak));
extern void (*__init_array_end [])      (void) __attribute__((weak));
extern void (*__fini_array_start[])     (void) __attribute__((weak));
extern void (*__fini_array_end[])       (void) __attribute__((weak));

extern "C" {
    /* Iterate over all the init routines.  */
    void __una_init_array (void)
    {
        size_t count;
        size_t i;

        count = __preinit_array_end - __preinit_array_start;
        for (i = 0; i < count; ++i) {
            __preinit_array_start[i] ();
        }

        #ifdef _HAVE_INIT_FINI
          _init ();
        #endif

        count = __init_array_end - __init_array_start;
        for (i = 0; i < count; ++i) {
           __init_array_start[i] ();
        }
   }

    void __una_fini_array(void)
    {
        int count = __fini_array_end - __fini_array_start;
        for (int i = 0; i < count; ++i) {
            __fini_array_start[i] ();
        }
    }
}

/**
 * @brief   _sbrk() allocates memory to the newlib heap and is used by malloc
 *          and others from the C library
 *
 * @brief   Dynamic memory allocation occurs through the system interface from
 *          the kernel, so this function should not be used.
 *
 * @param   incr Memory size
 * @return  Pointer to allocated memory
 */

extern "C" {

    void* __dso_handle = nullptr;

    void* _sbrk(ptrdiff_t incr)
    {
        kernel->app.log("_sbrk %d\n", incr);
        assert(0);  // Should not use in user app
        errno = ENOMEM;
        return (void*) -1;
    }

    void* malloc(size_t size)
    {
        return _malloc_r(NULL, size);
    }

    void free(void* ptr)
    {
        _free_r(NULL, ptr);
    }

    void* calloc(size_t __nmemb, size_t __size)
    {
        size_t bytes = __nmemb * __size;

        void* res = malloc(bytes);

        if (res) {
            memset(res, 0, bytes);
        }

        return res;
    }

    void* realloc(void* ptr, size_t __size)
    {
        return _realloc_r(NULL, ptr, __size);
    }

    void* _malloc_r(struct _reent *r, size_t size)
    {
        (void) r;
        void *ptr = kernel->mem.malloc(size);
        kernel->app.log("malloc 0x%08" PRIx32 " %u b\n", (uint32_t)(uintptr_t)ptr, (unsigned)size);
        return ptr;
    }

    void _free_r(struct _reent *r, void *ptr)
    {
        (void) r;
        if (ptr) {
            kernel->app.log("free   0x%08" PRIx32 "\n", (uint32_t)(uintptr_t)ptr);
            kernel->mem.free(ptr);
        }
    }

    void* _calloc_r(struct _reent *r, size_t nmemb, size_t size)
    {
        (void) r;
        void *ptr = _malloc_r(r, nmemb * size);
        if (ptr) {
            memset(ptr, 0, nmemb * size);
        }
        return ptr;
    }

    void* _realloc_r(struct _reent *r, void *ptr, size_t new_size)
    {
        // If ptr == NULL, realloc behaves like malloc.
        if (ptr == NULL) {
            return _malloc_r(r, new_size);
        }

        // If new_size == 0, release the block and return NULL.
        if (new_size == 0) {
            _free_r(r, ptr);
            return NULL;
        }

        // Allocate a new block of memory.
        void *new_ptr = _malloc_r(r, new_size);
        if (new_ptr == NULL) {
            // Selection failed, return NULL.
            return NULL;
        }

        // We copy the data from the old block to the new one (we copy the smaller of the two sizes).
        // Assume the old block contains at least new_size bytes for simplicity.
        // If exact copying is required, block size should be stored separately.
        memcpy(new_ptr, ptr, new_size);

        // Free the old block.
        _free_r(r, ptr);

        return new_ptr;
    }

    __attribute__((noreturn)) void __cxa_pure_virtual()
    {
        assert(false);
    }

    int __cxa_guard_acquire(uint64_t* g)
    {
        return !*(char*)(g);
    }

    void __cxa_guard_release(uint64_t* g)
    {
        *(char*)(g) = 1;
    }

    void __cxa_guard_abort(uint64_t*)
    {
    }

    int __cxa_atexit(void (*func)(void*), void* arg, void*)
    {
        return 0;
    }

    __attribute__((noreturn)) void __assert_func(const char *file,
                                                 int         line,
                                                 const char *func,
                                                 const char *failedexpr)
    {
        kernel->app.log("assert: %s %d %s %s\n", file, line, func, failedexpr);
        exit(-1);
    }

    __attribute__((noreturn)) void abort(void) {
        exit(-1);
    }

    __attribute__((noreturn)) void exitA(int status)
    {
        kernel->app.log("exit %d\n", status);
        kernel->app.exit(status);

        while (1) {}    /* Make sure we hang here */
    }

    __attribute__((noreturn)) void exit(int status)
    {
        __una_fini_array();

        exitA(status);

        while (1) {}    /* Make sure we hang here */
    }

}

namespace std
{
    void __throw_bad_alloc()
    {
        assert(false);
    }

    void __throw_bad_array_new_length()
    {
        assert(false);
    }

    void __throw_length_error(const char* msg)
    {
        (void) msg;

        assert(false);
    }
}

void* operator new(std::size_t size) noexcept
{
    return _malloc_r(nullptr, size);
}

void operator delete(void* ptr) noexcept
{
    _free_r(nullptr, ptr);
}

void* operator new[](std::size_t size)
{
    return operator new(size);
}

void operator delete[](void* ptr) noexcept
{
    operator delete(ptr);
}

void operator delete(void* ptr, std::size_t) noexcept
{
    operator delete(ptr);
}

void operator delete[](void* ptr, std::size_t) noexcept
{
    operator delete[](ptr);
}
