file(GLOB_RECURSE LIBS_SOURCES CONFIGURE_DEPENDS
    ${CMAKE_CURRENT_LIST_DIR}/Source/*.c
    ${CMAKE_CURRENT_LIST_DIR}/Source/*.cpp
)

file(GLOB_RECURSE LIBS_HEADERS CONFIGURE_DEPENDS
    ${CMAKE_CURRENT_LIST_DIR}/Header/*.h
    ${CMAKE_CURRENT_LIST_DIR}/Header/*.hpp
)

set(LIBS_INCLUDE_DIRS
    ${CMAKE_CURRENT_LIST_DIR}/Header
)